project:
  type: website
  output-dir: docs

website:
  title: "rcm-wiki"
  repo-url: https://github.com/alan-turing-institute/open-community-building.git
  repo-actions: [edit, issue]
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Contributing"
        file: contributing.qmd
  sidebar:
    - title: "Home"
      style: "docked"
      search: true
      contents:
        - section: "Basics"
          contents:
            - index.qmd
            - testpage.qmd
        - section: "Layout"
          contents:
            - index.qmd
            - about.qmd
            - testpage.qmd

    - title: "Contributing"
      contents:
        - section: "Basics"
          contents:
            - index.qmd
            - testpage.qmd
        - section: "Layout"
          contents:
            - index.qmd
            - about.qmd
            - testpage.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true



