project:
  type: website
  output-dir: docs

website:
  title: "rcm-wiki"
  repo-url: https://github.com/alan-turing-institute/open-community-building.git
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - docs/about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - index.qmd
          - docs/testpage.qmd
      - section: "Layout"
        contents:
          - index.qmd
          - docs/about.qmd
          - docs/testpage.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true



